version: '3.1'
services:
  stats-server:
    build: ./statservice
    container_name: ewm_stats_service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statservice
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statservice
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./mainservice
    container_name: ewm_main_service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - STATS_SERVER=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
